# Add this layer's directories to BitBake's search path.
BBPATH .= ":${LAYERDIR}"

# Locate recipes and recipe extensions supplied by this layer.
BBFILES += " \
    ${LAYERDIR}/recipes-*/*/*.bb \
    ${LAYERDIR}/recipes-*/*/*.bbappend \
"

BBFILE_COLLECTIONS += "reframe"
BBFILE_PATTERN_reframe = "^${LAYERDIR}/"
BBFILE_PRIORITY_reframe = "7"

LAYERSERIES_COMPAT_reframe = "wrynose"

LAYERDEPENDS_reframe = " \
    core \
    raspberrypi \
"
